project:
  type: website
  output-dir: docs

website:
  title: "PSF_CREONS"
  navbar:
    left:
      - href: index.qmd
        text: "Page d'accueil"
      - href: about.qmd
        text: "A propos du projet"
      - href: avancement.qmd
        text: "Avancement du projet"
      - href: modules.qmd
        text: "Modules de formation: protocole T2VA"
      - href: contacts.qmd
        text: "Ã‰quipe et contacts"
    right:
      - icon: github
        href: https://github.com/UMISOURCE/psf_creons
        aria-label: GitHub
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



